--TEST--
Sheet::dataValidationSize and Sheet::dataValidation read validations from xlsx (libxl 5.2.0+)
--EXTENSIONS--
excel
--SKIPIF--
<?php if (!method_exists("ExcelSheet", "dataValidation")) print "skip libxl 5.2.0+ required"; ?>
--DESCRIPTION--
libxl can only re-read data validations from files authored by Excel (or another
writer that emits standard <dataValidations> XML); its own addDataValidation()
output is not fed back into the reader on load. The fixture is therefore
generated by openpyxl rather than by this extension.
--FILE--
<?php
$book = new ExcelBook(null, null, true);
var_dump($book->loadFile(__DIR__ . '/datavalidation.xlsx'));
$sheet = $book->getSheet(0);

echo "size: " . $sheet->dataValidationSize() . "\n";

for ($i = 0; $i < $sheet->dataValidationSize(); $i++) {
    $d = $sheet->dataValidation($i);
    printf("[%d] type=%d op=%d r=%d-%d c=%d-%d v1=%s v2=%s\n",
        $i, $d['type'], $d['op'], $d['row_first'], $d['row_last'],
        $d['col_first'], $d['col_last'], $d['value1'], $d['value2']);
}

// out-of-range index returns false
var_dump($sheet->dataValidation(99));

echo "OK\n";
?>
--EXPECT--
bool(true)
size: 3
[0] type=1 op=0 r=2-5 c=1-1 v1=10 v2=100
[1] type=3 op=0 r=6-8 c=2-2 v1="Yes,No,Maybe" v2=
[2] type=2 op=6 r=1-3 c=3-3 v1=5 v2=
bool(false)
OK
